//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CukCuk.WebFresher032023.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CukCuk.WebFresher032023.Common.Resources.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng liên hệ MISA để được trợ giúp..
        /// </summary>
        public static string Error_Exception {
            get {
                return ResourceManager.GetString("Error_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác thực dữ liệu không thành công..
        /// </summary>
        public static string Validate_DevMessage {
            get {
                return ResourceManager.GetString("Validate_DevMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã món bị trùng lặp..
        /// </summary>
        public static string Validate_DuplicateFoodCode {
            get {
                return ResourceManager.GetString("Validate_DuplicateFoodCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã món ăn bắt buộc nhập..
        /// </summary>
        public static string Validate_FoodCodeRequired {
            get {
                return ResourceManager.GetString("Validate_FoodCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên món bắt buộc nhập..
        /// </summary>
        public static string Validate_FoodNameRequired {
            get {
                return ResourceManager.GetString("Validate_FoodNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá món ăn bắt buộc nhập..
        /// </summary>
        public static string Validate_FoodPriceRequired {
            get {
                return ResourceManager.GetString("Validate_FoodPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính bắt buộc nhập..
        /// </summary>
        public static string Validate_FoodUnitRequired {
            get {
                return ResourceManager.GetString("Validate_FoodUnitRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên vượt qua độ dài cho phép.
        /// </summary>
        public static string Validate_FullNameLengthMax {
            get {
                return ResourceManager.GetString("Validate_FullNameLengthMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy tài nguyên..
        /// </summary>
        public static string Validate_NotFoundAssests {
            get {
                return ResourceManager.GetString("Validate_NotFoundAssests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá món ăn là số lớn hơn 0..
        /// </summary>
        public static string Validate_PricePositive {
            get {
                return ResourceManager.GetString("Validate_PricePositive", resourceCulture);
            }
        }
    }
}
